import { Translations } from './types';

export const SCRIPT_URL = "https://script.google.com/macros/s/AKfycbwJoHd7yhjXVNnu49cUHQMWK4eLXeLcfaEnBcpsquF4GFdJPpyOItkC5TXrrumWAW8bng/exec";

export const TRANSLATIONS: Record<string, Translations> = {
  en: {
    title: "Volunteer Registration",
    subtitle: "Join us for Sangkranta Techno 2026 and be part of an amazing experience!",
    formProgress: "Form Progress",
    complete: "Complete",
    eventDates: "Event Dates",
    location: "Location",
    personalInfo: "Personal Information",
    fullNameKhmer: "Full Name (Khmer)",
    fullNameLatin: "Full Name (Latin)",
    gender: "Gender",
    dateOfBirth: "Date of Birth",
    select: "Select",
    male: "Male", female: "Female", other: "Other",
    academicInfo: "Academic Information",
    yearOfStudy: "Year of Study",
    department: "Department / Major",
    university: "University / Institution",
    studentId: "Student ID (For ITC)",
    contactInfo: "Contact Information",
    phoneNumber: "Phone Number",
    emailAddress: "Email Address",
    telegramUsername: "Telegram Username",
    address: "Address (optional)",
    interestsExp: "Interests & Experience",
    preferredTeam: "Preferred Volunteer Team",
    selectTeam: "Select one team you're most interested in",
    previousExp: "Previous Volunteer Experience",
    skills: "Skills & Talents",
    motivation: "Motivation for Volunteering",
    availability: "Availability & Commitment",
    eventAvailability: "Availability During Event",
    weeklyCommitment: "Weekly Commitment (hours)",
    commitmentStatement: "Commitment Statement",
    resetForm: "Reset",
    exportPDF: "Export",
    submitApp: "Submit Application",
    submitting: "Submitting...",
    appSubmitted: "Application Submitted! Check your Gmail.",
    thankYou: "Thank you for your interest in volunteering. We'll be in touch soon.",
    needHelp: "Need Help?",
    helpText: "If you have any questions about the registration process, feel free to contact us:",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    next: "Next",
    back: "Back",
    step: "Step",
    of: "of",
    startRegistration: "Start Registration"
  },
  km: {
    title: "ការចុះឈ្មោះអ្នកស្ម័គ្រចិត្ត",
    subtitle: "ចូលរួមជាមួយព្រឹត្តិការណ៍សង្ក្រាន្តតិចណូ ២០២៦ ដើម្បីទទួលបានបទពិសោធន៍ដ៏អស្ចារ្យ!",
    formProgress: "វឌ្ឍនភាព",
    complete: "រួចរាល់",
    eventDates: "កាលបរិច្ឆេទព្រឹត្តិការណ៍",
    location: "ទីតាំង",
    personalInfo: "ព័ត៌មានផ្ទាល់ខ្លួន",
    fullNameKhmer: "ឈ្មោះជាភាសាខ្មែរ",
    fullNameLatin: "ឈ្មោះជាអក្សរឡាតាំង",
    gender: "ភេទ",
    dateOfBirth: "ថ្ងៃខែឆ្នាំកំណើត",
    select: "ជ្រើសរើស",
    male: "ប្រុស", female: "ស្រី", other: "ផ្សេងទៀត",
    academicInfo: "ព័ត៌មានអំពីការសិក្សា",
    yearOfStudy: "ឆ្នាំសិក្សា",
    department: "ដេប៉ាតឺម៉ង់ / ជំនាញ",
    university: "សាកលវិទ្យាល័យ / ស្ថាប័ន",
    studentId: "លេខសម្គាល់និស្សិត (សម្រាប់ ITC)",
    contactInfo: "ព័ត៌មានទំនាក់ទំនង",
    phoneNumber: "លេខទូរស័ព្ទ",
    emailAddress: "អ៊ីមែល",
    telegramUsername: "គណនី Telegram (Username/Link)",
    address: "អាសយដ្ឋានបច្ចុប្បន្ន (មិនចាំបាច់)",
    interestsExp: "ចំណាប់អារម្មណ៍ និងបទពិសោធន៍",
    preferredTeam: "ក្រុមការងារដែលចង់ចូលរួម",
    selectTeam: "សូមជ្រើសរើសក្រុមការងារដែលអ្នកចាប់អារម្មណ៍បំផុត",
    previousExp: "បទពិសោធន៍ការងារស្ម័គ្រចិត្តពីមុន",
    skills: "ជំនាញ និងទេពកោសល្យ",
    motivation: "មូលហេតុនៃការចូលរួម",
    availability: "ពេលវេលា និងការប្តេជ្ញាចិត្ត",
    eventAvailability: "ពេលវេលាដែលអាចចូលរួមក្នុងកម្មវិធី",
    weeklyCommitment: "ពេលវេលាអាចចំណាយប្រចាំសប្តាហ៍ (ម៉ោង)",
    commitmentStatement: "ការប្តេជ្ញាចិត្ត",
    resetForm: "កំណត់ឡើងវិញ",
    exportPDF: "ទាញយកឯកសារ",
    submitApp: "បញ្ជូនពាក្យសុំ",
    submitting: "កំពុងបញ្ជូន...",
    appSubmitted: "ការចុះឈ្មោះជោគជ័យ! សូមពិនិត្យមើលអ៊ីមែលរបស់អ្នក។",
    thankYou: "សូមអរគុណចំពោះការចូលរួមរបស់អ្នក។ យើងនឹងទាក់ទងទៅអ្នកក្នុងពេលឆាប់ៗនេះ។",
    needHelp: "ត្រូវការជំនួយ?",
    helpText: "ប្រសិនបើអ្នកមានសំណួរអំពីដំណើរការចុះឈ្មោះ សូមទាក់ទងមកយើងខ្ញុំតាមរយៈ៖",
    darkMode: "របៀបងងឹត",
    lightMode: "របៀបភ្លឺ",
    next: "បន្ទាប់",
    back: "ត្រឡប់ក្រោយ",
    step: "ជំហានទី",
    of: "នៃ",
    startRegistration: "ចាប់ផ្តើមចុះឈ្មោះ"
  }
};

export const TEAMS = [
  "Marketing", "Media", "Protocol", "Logistic", "Religion", "Decor", "Float", "Entertainment"
];